item/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from price import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path ('price/', include ('price.urls')),
    url (r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

price/urls.py
from django.conf.urls import url
from django.urls import path


from . import views

app_name = 'price'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('add/', views.PersonCreateView.as_view(), name='add'),
    path ('<int:pk>/', views.DetailView.as_view (), name='detail'),
    path('search/', views.search_item, name='search_item_view'),

    # /price/2/update
    path('update/<int:pk>', views.ItemUpdate.as_view(), name='item_update'),

    # /price/2/delete
    path ('<int:pk>/delete', views.ItemDelete.as_view(), name='item_delete'),

    url (r'^import/', views.import_data, name="import"),
    url (r'^ticket/', views.get_ticket, name='ticket'),
]

price/models.py
from django.db import models

# Create your models here.
from django.db import models
import datetime
from django.utils import timezone

from django.dispatch import receiver
import os
import time

class  Item(models.Model):
    mark = models.CharField('Mark', max_length=200, blank=True)
    name = models.CharField('Name', max_length=200, blank=True)
    fr_price = models.IntegerField ('Franch Price', default=0, blank=True)
    cn_price = models.IntegerField ('China Price', default=0, blank=True)
    sale_price = models.IntegerField('sale Price', default=0, blank=True)
    promo_price = models.IntegerField('promo Price', default=0, blank=True)
    quantity = models.IntegerField('Quantity', default=0, blank=True)
    sold_quantity = models.IntegerField('Sold Quantity', default=0, blank=True)
    image = models.ImageField('image', blank=True, upload_to='Images')

    def __str__(self):
        return self.name

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


@receiver(models.signals.post_delete, sender=Item)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Deletes file from filesystem
    when corresponding `MediaFile` object is deleted.
    """
    if instance.image:
        if os.path.isfile(instance.image.path):
            os.remove(instance.image.path)

@receiver (models.signals.pre_save, sender=Item)
def auto_delete_file_on_change(sender, instance, *args, **kwargs):
    if not instance.pk:
        return False

    try:
        old_image = None
        if(Item.objects.get (pk=instance.pk).image):
            old_image = Item.objects.get (pk=instance.pk).image
        else:
            return False
        print(old_image.path)
    except Item.DoesNotExist:
        return False

    new_image = instance.image
    if not old_image == new_image:
        if os.path.isfile (old_image.path):
            os.remove (old_image.path)

price/forms.py
from django import forms
import time

class SNCF(forms.Form):
    origin = forms.CharField(label='出发点', max_length=100,required=False, initial='Belfort-Montbeliard')
    destination = forms.CharField (label='目的地', max_length=100, required=False,initial='Paris')
    departureDate = forms.DateField(label='出发时间',required=False, widget = forms.DateInput(attrs={'id':'datepicker'}),initial=str(time.strftime ('%Y-%m-%d', time.localtime (time.time ()))))


class UploadFileForm(forms.Form):
    file = forms.FileField()

price/views.py
import json
import random
import time
import datetime
import requests

from django.contrib import messages
from django.http import HttpResponseBadRequest
from django.shortcuts import render, redirect

from django.views import generic
from django.urls import reverse_lazy
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Item
from .forms import SNCF, UploadFileForm


def index(request):
    # page = request.GET.get ('page', 1)

    all_item_list = Item.objects.all()

    # paginator = Paginator (all_item_list, 9)
    # try:
    #     items = paginator.page (page)
    # except PageNotAnInteger:
    #     items = paginator.page (1)
    # except EmptyPage:
    #     items = paginator.page (paginator.num_pages)
    return render (request, 'price/index.html', { 'items': all_item_list })


class DetailView (generic.DetailView):
    model = Item
    template_name = 'price/detail.html'


class PersonCreateView (generic.CreateView):
    model = Item
    template_name = 'price/add.html'
    fields = '__all__'


    success_url = reverse_lazy ('price:index')


class ItemUpdate (generic.UpdateView):
    model = Item
    fields = '__all__'
    template_name = 'price/update.html'
    success_url = reverse_lazy('price:index')


class ItemDelete (generic.DeleteView):
    model = Item
    success_url = reverse_lazy ('price:index')


def search_item(request):
    ''' This could be your actual view or a new one '''
    # Your code
    if request.method == 'GET':
        # If the form is submitted
        search_query = request.GET.get ('search_box', None)
        all_item_list = Item.objects.filter (name__contains=search_query)
        context = {
            'items': all_item_list,
        }
        return render (request, 'price/index.html', context)


def import_data(request):
    if request.method == "POST":
        form = UploadFileForm (request.POST,
                               request.FILES)

        if form.is_valid ():
            request.FILES['file'].save_to_database (
                model=Item,
                mapdicts=[
                    ['name', 'fr_price', 'cn_price', 'sale_price', 'quantity', 'sold_quantity', 'pub_date']]
            )
            return redirect ('price/index')
        else:
            return HttpResponseBadRequest ()
    else:
        form = UploadFileForm ()
        return render (
            request,
            'upload_form.html',
            {
                'form': form,
                'title': 'Import excel data into database example',
                'header': 'Please upload sample-data.xls:'
            })


# TGV
def get_ticket(request):
    if request.method == 'POST':
        form = SNCF (request.POST)
        if form.is_valid ():
            postUrl = 'https://www.oui.sncf/proposition/rest/best-prices/in-range'
            # payloadData数据
            index = 3
            HCode = "HC200211251"
            departureDate = request.POST.get ("departureDate") + "T06:00:00"
            date = datetime.datetime.strptime (departureDate, '%Y-%m-%dT%H:%M:%S')
            today = datetime.datetime.now ()
            date1 = datetime.datetime.strptime (request.POST.get ("departureDate"), '%Y-%m-%d')

            birthDate = "1995-03-15T00:00:00"
            if (date + datetime.timedelta (days=-3)).strftime ('%Y-%m-%d') > time.strftime ('%Y-%m-%d',
                                                                                            time.localtime (
                                                                                                time.time ())):
                rangeStart = (date + datetime.timedelta (days=-3)).strftime ('%Y-%m-%dT%H:%M:%S')
            else:
                rangeStart = time.strftime ('%Y-%m-%dT%H:%M:%S', time.localtime (time.time ()))

                index = (date1 - today).days + 1
            rangeEnd = (date + datetime.timedelta (days=+3)).strftime ('%Y-%m-%dT%H:%M:%S')

            origin = request.POST.get("origin")

            destination = request.POST.get("destination")

            user_agents = [
                "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; AcooBrowser; .NET CLR 1.1.4322; .NET CLR 2.0.50727)",
                "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0; Acoo Browser; SLCC1; .NET CLR 2.0.50727; Media Center PC 5.0; .NET CLR 3.0.04506)",
                "Mozilla/4.0 (compatible; MSIE 7.0; AOL 9.5; AOLBuild 4337.35; Windows NT 5.1; .NET CLR 1.1.4322; .NET CLR 2.0.50727)",
                "Mozilla/5.0 (Windows; U; MSIE 9.0; Windows NT 9.0; en-US)",
                "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Win64; x64; Trident/5.0; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET CLR 2.0.50727; Media Center PC 6.0)",
                "Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.0; Trident/4.0; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET CLR 1.0.3705; .NET CLR 1.1.4322)",
                "Mozilla/4.0 (compatible; MSIE 7.0b; Windows NT 5.2; .NET CLR 1.1.4322; .NET CLR 2.0.50727; InfoPath.2; .NET CLR 3.0.04506.30)",
                "Mozilla/5.0 (Windows; U; Windows NT 5.1; zh-CN) AppleWebKit/523.15 (KHTML, like Gecko, Safari/419.3) Arora/0.3 (Change: 287 c9dfb30)",
                "Mozilla/5.0 (X11; U; Linux; en-US) AppleWebKit/527+ (KHTML, like Gecko, Safari/419.3) Arora/0.6",
                "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.2pre) Gecko/20070215 K-Ninja/2.1.1",
                "Mozilla/5.0 (Windows; U; Windows NT 5.1; zh-CN; rv:1.9) Gecko/20080705 Firefox/3.0 Kapiko/3.0",
                "Mozilla/5.0 (X11; Linux i686; U;) Gecko/20070322 Kazehakase/0.4.5",
                "Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.8) Gecko Fedora/1.9.0.8-1.fc10 Kazehakase/0.5.6",
                "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.56 Safari/535.11",
                "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/535.20 (KHTML, like Gecko) Chrome/19.0.1036.7 Safari/535.20",
                "Opera/9.80 (Macintosh; Intel Mac OS X 10.6.8; U; fr) Presto/2.9.168 Version/11.52",
            ]

            print (date)
            payloadData = {"query":
                               {"origin": origin,
                                "originCode": "",
                                "originLocation":
                                    {"id": None,
                                     "label": None,
                                     "longitude": None,
                                     "latitude": None,
                                     "type": None,
                                     "country": None,
                                     "stationCode": "",
                                     "stationLabel": None},
                                "destination": destination,
                                "destinationCode": "", "destinationLocation":
                                    {"id": None,
                                     "label": None,
                                     "longitude": None,
                                     "latitude": None,
                                     "type": None,
                                     "country": None,
                                     "stationCode": "",
                                     "stationLabel": None},
                                "via": None,
                                "viaCode": None,
                                "viaLocation": None,
                                "directTravel": True,
                                "asymmetrical": False,
                                "professional": False,
                                "customerAccount": False,
                                "oneWayTravel": True,
                                "departureDate": departureDate,
                                "returnDate": None,
                                "travelClass": "SECOND",
                                "country": "FR",
                                "language": "fr",
                                "busBestPriceOperator": None,
                                "passengers": [
                                    {"travelerId": None,
                                     "profile": "YOUNG",
                                     "age": 12,
                                     "birthDate": birthDate,
                                     "fidelityCardType": "NONE",
                                     "fidelityCardNumber": "",
                                     "commercialCardNumber": HCode,
                                     "commercialCardType": "HAPPY_CARD",
                                     "promoCode": None,
                                     "lastName": None,
                                     "firstName": None,
                                     "phoneNumer": None,
                                     "hanInformation": None}],
                                "animals": [],
                                "bike": "NONE",
                                "withRecliningSeat": False,
                                "physicalSpace": None,
                                "fares": [],
                                "withBestPrices": False,
                                "highlightedTravel": None,
                                "nextOrPrevious": False,
                                "source": "FORM_SUBMIT",
                                "targetPrice": None,
                                "han": False,
                                "outwardScheduleType": "BY_DEPARTURE_DATE",
                                "inwardScheduleType": "BY_DEPARTURE_DATE",
                                "currency": None,
                                "codeFce": None,
                                "companions": [],
                                "asymetricalItinerary": {}},
                           "rangeEnd": rangeEnd,

price/templates/price/add.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block mainbody %}
<div class="container">
    <h1>Add Item</h1>
    <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" value="Save" class="btn btn-success">Save Item</button>
    </form>
</div>

{% endblock %}

price/templates/price/detail.html
{%extends "base.html" %}
{% block mainbody %}
<div class="container">
    <div >
        <form action="{% url 'price:item_delete' item.id %}" method="post" class="form-inline my-2 my-lg-0">
                    {% csrf_token %}
                    <input type="hidden" name="item_id" value="{{item.id}}"/>
                    <a class="btn btn-primary" role="button" href="{% url 'price:item_update' item.id %}">编辑</a>
                    <button type="submit" class="btn btn-danger" style="position : relative; left: 80%; " >删除</button>
        </form>
    </div>
    <ul class="list-group">
        <li class="list-group-item"><h6 class="text-primary">品牌：</h6>{{ item.mark }}</li>
        <li class="list-group-item"><h6 class="text-primary">名称：</h6>{{ item.name }}</li>
        <li class="list-group-item"><h6 class="text-primary">国内价格：</h6>{{ item.cn_price }}</li>
        <li class="list-group-item"><h6 class="text-primary">法国价格：</h6>{{ item.fr_price }}</li>
        <li class="list-group-item"><h6 class="text-primary">售价：</h6>{{ item.sold_price }}</li>
        <li class="list-group-item"><h6 class="text-primary">活动价：</h6>{{ item.promo_price }}</li>
        <li class="list-group-item"><h6 class="text-primary">数量：</h6>{{ item.quantity }}</li>
        <li class="list-group-item"><h6 class="text-primary">已售数量：</h6>{{ item.sold_quantity }}</li>

        {% if item.image %}
            <li class="list-group-item"><img src="{{ item.image.url }}" class="rounded float-left" width="600" height="300"></li>
        {% endif %}
    </ul>


</div>
{% endblock %}

price/templates/price/index.html
{%extends "base.html" %}
{% load staticfiles %}
{% load bootstrap4 %}
{% block mainbody %}
<div class="container">

    <table class="sortable table table-striped table-bordered table-hover">
        <thead class="thead-dark">
        <tr class="sticky-top">
            <th scope="col">品牌</th>
            <th scope="col">名称</th>
            <th scope="col">定价</th>
            <th scope="col">活动价</th>
        </tr>
        </thead>
        <tbody>
        {% for item in items %}
        <tr>
            <td>{{ item.mark }}</td>
            <th><a href="{% url 'price:detail' item.id %}">{{ item.name }}</a></th>
            <td>{{ item.sale_price }}</td>
            <td>{{ item.promo_price }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

    <!--{% if items.has_other_pages %}
    <ul class="pagination">
        {% if items.has_previous %}
        <li class="active"><a class="page-link" href="?page={{ items.previous_page_number }}">Previous</a></li>
        {% else %}
        <li class="disabled"><a class="page-link"><span>Previous</span></a></li>
        {% endif %}
        {% for i in items.paginator.page_range %}
        {% if items.number == i %}
        <li class="page-item active">
            <a class="page-link" href="#"><span>{{ i }} <span class="sr-only">(current)</span></span></a>
        </li>
        {% else %}
        <li class="active"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        {% if items.has_next %}
        <li class="active"><a class="page-link" href="?page={{ items.next_page_number }}">Next</a></li>
        {% else %}
        <li class="disabled"><a class="page-link"><span>Next</span></a></li>
        {% endif %}
    </ul>
    {% endif %}-->

</div>

{% endblock %}

price/templates/price/update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block mainbody %}
<div class="container">
    <h1>Update Item</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" value="Update" class="btn btn-success">Save Item</button>
    </form>
</div>
{% endblock %}