item/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from price import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path ('price/', include ('price.urls')),
    url (r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

price/urls.py
from django.conf.urls import url
from django.urls import path


from . import views

app_name = 'price'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('add/', views.PersonCreateView.as_view(), name='add'),
    path ('<int:pk>/', views.DetailView.as_view (), name='detail'),
    path('search/', views.search_item, name='search_item_view'),

    # /price/2/update
    path('update/<int:pk>', views.ItemUpdate.as_view(), name='item_update'),

    # /price/2/delete
    path ('<int:pk>/delete', views.ItemDelete.as_view(), name='item_delete'),

    url (r'^import/', views.import_data, name="import"),
    url (r'^ticket/', views.get_ticket, name='ticket'),
]

price/models.py
from django.db import models

# Create your models here.
from django.db import models
import datetime
from django.utils import timezone

from django.dispatch import receiver
import os
import time

class  Item(models.Model):
    mark = models.CharField('Mark', max_length=200, blank=True)
    name = models.CharField('Name', max_length=200, blank=True)
    fr_price = models.IntegerField ('Franch Price', default=0, blank=True)
    cn_price = models.IntegerField ('China Price', default=0, blank=True)
    sale_price = models.IntegerField('sale Price', default=0, blank=True)
    promo_price = models.IntegerField('promo Price', default=0, blank=True)
    quantity = models.IntegerField('Quantity', default=0, blank=True)
    sold_quantity = models.IntegerField('Sold Quantity', default=0, blank=True)
    image = models.ImageField('image', blank=True, upload_to='Images')

    def __str__(self):
        return self.name

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


@receiver(models.signals.post_delete, sender=Item)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Deletes file from filesystem
    when corresponding `MediaFile` object is deleted.
    """
    if instance.image:
        if os.path.isfile(instance.image.path):
            os.remove(instance.image.path)

@receiver (models.signals.pre_save, sender=Item)
def auto_delete_file_on_change(sender, instance, *args, **kwargs):
    if not instance.pk:
        return False

    try:
        old_image = None
        if(Item.objects.get (pk=instance.pk).image):
            old_image = Item.objects.get (pk=instance.pk).image
        else:
            return False
        print(old_image.path)
    except Item.DoesNotExist:
        return False

    new_image = instance.image
    if not old_image == new_image:
        if os.path.isfile (old_image.path):
            os.remove (old_image.path)

price/forms.py
from django import forms
import time

class SNCF(forms.Form):
    origin = forms.CharField(label='出发点', max_length=100,required=False, initial='Belfort-Montbeliard')
    destination = forms.CharField (label='目的地', max_length=100, required=False,initial='Paris')
    departureDate = forms.DateField(label='出发时间',required=False, widget = forms.DateInput(attrs={'id':'datepicker'}),initial=str(time.strftime ('%Y-%m-%d', time.localtime (time.time ()))))


class UploadFileForm(forms.Form):
    file = forms.FileField()

price/views.py
import json
import random
import time
import datetime
import requests

from django.contrib import messages
from django.http import HttpResponseBadRequest
from django.shortcuts import render, redirect

from django.views import generic
from django.urls import reverse_lazy
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Item
from .forms import SNCF, UploadFileForm


def index(request):
    # page = request.GET.get ('page', 1)

    all_item_list = Item.objects.all()

    # paginator = Paginator (all_item_list, 9)
    # try:
    #     items = paginator.page (page)
    # except PageNotAnInteger:
    #     items = paginator.page (1)
    # except EmptyPage:
    #     items = paginator.page (paginator.num_pages)
    return render (request, 'price/index.html', { 'items': all_item_list })


class DetailView (generic.DetailView):
    model = Item
    template_name = 'price/detail.html'


class PersonCreateView (generic.CreateView):
    model = Item
    template_name = 'price/add.html'
    fields = '__all__'


    success_url = reverse_lazy ('price:index')


class ItemUpdate (generic.UpdateView):
    model = Item
    fields = '__all__'
    template_name = 'price/update.html'
    success_url = reverse_lazy('price:index')


class ItemDelete (generic.DeleteView):
    model = Item
    success_url = reverse_lazy ('price:index')


def search_item(request):
    ''' This could be your actual view or a new one '''
    # Your code
    if request.method == 'GET':
        # If the form is submitted
        search_query = request.GET.get ('search_box', None)
        all_item_list = Item.objects.filter (name__contains=search_query)
        context = {
            'items': all_item_list,
        }
        return render (request, 'price/index.html', context)


def import_data(request):
    if request.method == "POST":
        form = UploadFileForm (request.POST,
                               request.FILES)

        if form.is_valid ():
            request.FILES['file'].save_to_database (
                model=Item,
                mapdicts=[
                    ['name', 'fr_price', 'cn_price', 'sale_price', 'quantity', 'sold_quantity', 'pub_date']]
            )
            return redirect ('price/index')
        else:
            return HttpResponseBadRequest ()
    else:
        form = UploadFileForm ()
        return render (
            request,
            'upload_form.html',
            {
                'form': form,
                'title': 'Import excel data into database example',
                'header': 'Please upload sample-data.xls:'
            })


# TGV
def get_ticket(request):
    if request.method == 'POST':
        form = SNCF (request.POST)
        if form.is_valid ():
            postUrl = 'https://www.oui.sncf/proposition/rest/best-prices/in-range'
            # payloadData数据
            index = 3
            HCode = "HC200211251"
            departureDate = request.POST.get ("departureDate") + "T06:00:00"
            date = datetime.datetime.strptime (departureDate, '%Y-%m-%dT%H:%M:%S')
            today = datetime.datetime.now ()
            date1 = datetime.datetime.strptime (request.POST.get ("departureDate"), '%Y-%m-%d')

            birthDate = "1995-03-15T00:00:00"
            if (date + datetime.timedelta (days=-3)).strftime ('%Y-%m-%d') > time.strftime ('%Y-%m-%d',
                                                                                            time.localtime (
                                                                                                time.time ())):
                rangeStart = (date + datetime.timedelta (days=-3)).strftime ('%Y-%m-%dT%H:%M:%S')
            else:
                rangeStart = time.strftime ('%Y-%m-%dT%H:%M:%S', time.localtime (time.time ()))

                index = (date1 - today).days + 1
            rangeEnd = (date + datetime.timedelta (days=+3)).strftime ('%Y-%m-%dT%H:%M:%S')

            origin = request.POST.get("origin")

            destination = request.POST.get("destination")

            user_agents = [
                "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; AcooBrowser; .NET CLR 1.1.4322; .NET CLR 2.0.50727)",
                "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0; Acoo Browser; SLCC1; .NET CLR 2.0.50727; Media Center PC 5.0; .NET CLR 3.0.04506)",
                "Mozilla/4.0 (compatible; MSIE 7.0; AOL 9.5; AOLBuild 4337.35; Windows NT 5.1; .NET CLR 1.1.4322; .NET CLR 2.0.50727)",
                "Mozilla/5.0 (Windows; U; MSIE 9.0; Windows NT 9.0; en-US)",
                "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Win64; x64; Trident/5.0; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET CLR 2.0.50727; Media Center PC 6.0)",
                "Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.0; Trident/4.0; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET CLR 1.0.3705; .NET CLR 1.1.4322)",
                "Mozilla/4.0 (compatible; MSIE 7.0b; Windows NT 5.2; .NET CLR 1.1.4322; .NET CLR 2.0.50727; InfoPath.2; .NET CLR 3.0.04506.30)",
                "Mozilla/5.0 (Windows; U; Windows NT 5.1; zh-CN) AppleWebKit/523.15 (KHTML, like Gecko, Safari/419.3) Arora/0.3 (Change: 287 c9dfb30)",
                "Mozilla/5.0 (X11; U; Linux; en-US) AppleWebKit/527+ (KHTML, like Gecko, Safari/419.3) Arora/0.6",
                "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.2pre) Gecko/20070215 K-Ninja/2.1.1",
                "Mozilla/5.0 (Windows; U; Windows NT 5.1; zh-CN; rv:1.9) Gecko/20080705 Firefox/3.0 Kapiko/3.0",
                "Mozilla/5.0 (X11; Linux i686; U;) Gecko/20070322 Kazehakase/0.4.5",
                "Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.8) Gecko Fedora/1.9.0.8-1.fc10 Kazehakase/0.5.6",
                "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.56 Safari/535.11",
                "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/535.20 (KHTML, like Gecko) Chrome/19.0.1036.7 Safari/535.20",
                "Opera/9.80 (Macintosh; Intel Mac OS X 10.6.8; U; fr) Presto/2.9.168 Version/11.52",
            ]

            print (date)
            payloadData = {"query":
                               {"origin": origin,
                                "originCode": "",
                                "originLocation":
                                    {"id": None,
                                     "label": None,
                                     "longitude": None,
                                     "latitude": None,
                                     "type": None,
                                     "country": None,
                                     "stationCode": "",
                                     "stationLabel": None},
                                "destination": destination,
                                "destinationCode": "", "destinationLocation":
                                    {"id": None,
                                     "label": None,
                                     "longitude": None,
                                     "latitude": None,
                                     "type": None,
                                     "country": None,
                                     "stationCode": "",
                                     "stationLabel": None},
                                "via": None,
                                "viaCode": None,
                                "viaLocation": None,
                                "directTravel": True,
                                "asymmetrical": False,
                                "professional": False,
                                "customerAccount": False,
                                "oneWayTravel": True,
                                "departureDate": departureDate,
                                "returnDate": None,
                                "travelClass": "SECOND",
                                "country": "FR",
                                "language": "fr",
                                "busBestPriceOperator": None,
                                "passengers": [
                                    {"travelerId": None,
                                     "profile": "YOUNG",
                                     "age": 12,
                                     "birthDate": birthDate,
                                     "fidelityCardType": "NONE",
                                     "fidelityCardNumber": "",
                                     "commercialCardNumber": HCode,
                                     "commercialCardType": "HAPPY_CARD",
                                     "promoCode": None,
                                     "lastName": None,
                                     "firstName": None,
                                     "phoneNumer": None,
                                     "hanInformation": None}],
                                "animals": [],
                                "bike": "NONE",
                                "withRecliningSeat": False,
                                "physicalSpace": None,
                                "fares": [],
                                "withBestPrices": False,
                                "highlightedTravel": None,
                                "nextOrPrevious": False,
                                "source": "FORM_SUBMIT",
                                "targetPrice": None,
                                "han": False,
                                "outwardScheduleType": "BY_DEPARTURE_DATE",
                                "inwardScheduleType": "BY_DEPARTURE_DATE",
                                "currency": None,
                                "codeFce": None,
                                "companions": [],
                                "asymetricalItinerary": {}},
                           "rangeEnd": rangeEnd,

price/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load bootstrap4 %}
{% load widget_tweaks %}
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
          integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css"
          integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
          crossorigin="anonymous">
    <link rel="stylesheet"
          href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css"
          type="text/css"
          media="all"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js"
            type="text/javascript"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'js/sorttable.js' %}"></script>
    <meta charset="UTF-8">
    <title>Price</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
    <a class="navbar-brand" href="#">Menu</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'price:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'price:add' %}">Add <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'admin:index' %}price/item/import">Upload<span class="sr-only"></span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'admin:index' %}price/item/export">Export<span class="sr-only"></span></a>
            </li>
             <li class="nav-item active">
                <a class="nav-link" href="{% url 'price:ticket' %}">Ticket<span class="sr-only"></span></a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url 'price:search_item_view' %}" method="get">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search"
                   name="search_box">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit" id="search_submit">Search</button>
        </form>

    </div>
</nav>
{% block mainbody %}
<p>original</p>
{% endblock %}

</body>

</html>

price/templates/ticket.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block mainbody %}
<div class="container">
    <form action="/price/ticket/" method="post">
        {% csrf_token %}

        {% for field in form %}
        <div class="form-group">
            {{ field.label_tag }}
            {% render_field field class="form-control" %}
        </div>
        {% endfor %}

        <input type="submit" class="btn btn-primary" value="Submit">

    </form>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li>{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</div>

      <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
      <link rel="stylesheet" href="/resources/demos/style.css">
      <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
      <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
      <script>
      $( function() {
        $( "#datepicker" ).datepicker({
                dateFormat: "yy-mm-dd"
            });
      } );
      </script>
{% endblock %}

price/templates/upload_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block mainbody %}
    <div class="container">
        <form enctype="multipart/form-data"  method="post">
            {% csrf_token %}
            <table>
                {{ form|crispy }}
            </table>

            <input type="submit" class="btn btn-primary" value="Submit" >
        </form>
    </div>
{% endblock %}